### ISSUE TITLE
:label:[デザインパターン勉強]

### ISSUE THREAD

**Issue by takacube** [takacube/ToDoOraganize#255]
## ToDo
GoF 23のデザインパターンをとりあえずアイディアとして持っておく．この知識を保有しながらデータモデリングを実施していき必要なデザインパターンはどれなのかを当てはめていく．

生成に関する
- [ ] [Abstract Factory](https://qiita.com/i-tanaka730/items/21c52a36bb2ffded5dde)
- [ ] [Builder](https://qiita.com/i-tanaka730/items/10596f3c7a7a2df806e2)
- [ ] [Factory Method](https://qiita.com/i-tanaka730/items/1f521866c7d699ddd093)
- [ ] [Prototype](https://qiita.com/i-tanaka730/items/c0177e17c9df5f379925)
- [ ] [Singleton](https://qiita.com/i-tanaka730/items/507d323f1ebb3167b067)

構造に関する
- [ ] [Adapter](https://qiita.com/i-tanaka730/items/da8731c219c921d30a59)
- [ ] [Bridge](https://qiita.com/i-tanaka730/items/91debf39a7f64ef6cb23)
- [ ] [Composite](https://qiita.com/i-tanaka730/items/577ca124f05bfe172248)
- [ ] [Decorator](https://qiita.com/i-tanaka730/items/a0f53d70b0830cfd150b)
- [ ] [Facade](https://qiita.com/i-tanaka730/items/911604bcd4136684ff1c)
- [ ] [Flyweight](https://qiita.com/i-tanaka730/items/ed32b9a7c3f9f72b59ef)
- [ ] [Proxy](https://qiita.com/i-tanaka730/items/47efbab5eccc2d36759f)

振る舞いに関する
- [ ] [Chain of Responsibility](https://qiita.com/i-tanaka730/items/073c106c58d7c74c1706)
- [ ] [Command](https://qiita.com/i-tanaka730/items/6f8c3423eda95c230f3b)
- [ ] [Interpreter](https://qiita.com/i-tanaka730/items/adf5090cdbfd55cbc9b5)
- [ ] [Iterator](https://qiita.com/i-tanaka730/items/7c178409a4d5c1e4e42b)
- [ ] [Mediator](https://qiita.com/i-tanaka730/items/9f96d28d32ab3c9099d9)
- [ ] [Memento](https://qiita.com/i-tanaka730/items/c664aeec431da492f5de)
- [ ] [Observer](https://qiita.com/i-tanaka730/items/b69cd773d81e044a2ec9)
- [ ] [State](https://qiita.com/i-tanaka730/items/49ee4e3daa3aeaf6e0b5)
- [ ] [Strategy](https://qiita.com/i-tanaka730/items/4d00c884b7ce1594f42a)
- [ ] [Template Method](https://qiita.com/i-tanaka730/items/dbeb82ac44c031fe8df9)
- [ ] [Visitor](https://qiita.com/i-tanaka730/items/2e2d4fac2075b3e45ef7)

## ゴール
概要の理解をする
## メモ
